version: '2'
services:
    web:
        # build: .
        image: my_flask_app
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        # depends_on:
        #     - redis
    # redis:
    #     image: redis