GRANT All PRIVILEGES ON *.*  to 'root'@'localhost' IDENTIFIED BY '1'  WITH GRANT OPTION;
GRANT All PRIVILEGES ON *.*  to 'root'@'127.0.0.1' IDENTIFIED BY '1'  WITH GRANT OPTION;
GRANT All PRIVILEGES ON *.*  to 'root'@'::1' IDENTIFIED BY '1'  WITH GRANT OPTION;
GRANT All PRIVILEGES ON *.*  to 'root'@'%' IDENTIFIED BY '1'  WITH GRANT OPTION;
flush privileges;