GRANT All PRIVILEGES ON *.*  to 'root'@'localhost' IDENTIFIED BY 'root'  WITH GRANT OPTION;
GRANT All PRIVILEGES ON *.*  to 'root'@'127.0.0.1' IDENTIFIED BY 'root'  WITH GRANT OPTION;
GRANT All PRIVILEGES ON *.*  to 'root'@'::1' IDENTIFIED BY 'root'  WITH GRANT OPTION;
GRANT All PRIVILEGES ON *.*  to 'root'@'%' IDENTIFIED BY 'root'  WITH GRANT OPTION;
flush privileges;